server:
  port: 8092

spring:
  cloud:
    config:
      name: profile-service

  datasource:
    url: jdbc:postgresql://localhost:5433/profile
    username: postgres
    password: secret
  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc: time_zone=UTC
  jackson:
    time-zone: UTC

info:
  build:
    version: "1.0.2"
  contact:
    email: "hoangtanphuquoc@gmail.com"
    phone: "0333507708"
