server:
  port: 8092

spring:
  cloud:
    config:
      name: profile-service

  datasource:
    url: jdbc:postgresql://localhost:5433/profile
    username: postgres
    password: secret
  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc: time_zone=UTC
  jackson:
    time-zone: UTC

build:
  version: "1.0.0"

application:
  name: "profile-service"
  description: Profile Service
  version: "1.2.3"
  profile: "dev"
  message: "Welcome to the Profile Service"
  email: "{cipher}c969c667f04d20068aae2f1d1a7523c714d272b5c13974e131b70e05b9291b01e74150f851baa5e155a187fb64a9c0e4"
