server:
  port: ${SERVER_PORT:8080}

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
          lower-case-service-id: true

logging:
  level:
    org.springframework.cloud.gateway: DEBUG

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_DEFAULT_ZONE:http://localhost:8761/eureka}

info:
  application:
    name: ${spring.application.name}
    description: Gateway Service for Domain Driven Deign LinkedHub
    version: ${APP_VERSION:1.0.0}
  env:
    enabled: ${ENV_ENABLED:true}